/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-08-27 09:24:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import jp.co.mtrx.hms.service.*;
import jp.co.mtrx.hms.model.*;

public final class patientList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset = Shift_JIS;charset=Shift_JIS");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>患者一覧</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>患者一覧</h1>\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");

	Service service = (Service)application.getAttribute("service");
	List<Patient> patients = service.getPatients();

      out.write("\r\n");
      out.write("<table border=\"1\" width=\"400\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th width=\"20%\">ID</th>\r\n");
      out.write("\t<th width=\"20%\">名前</th>\r\n");
      out.write("\t<th width=\"20%\">血液型</th>\r\n");
      out.write("\t<th width=\"20%\">身長</th>\r\n");
      out.write("\t<th width=\"20%\"></th>\r\n");
      out.write("</tr>\r\n");

	for(Patient patient : patients){
		if(patient == null)
		continue;//リストの実装は配列なのでnullがありえる

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><a href=\"displayPatientUpdate?id=");
      out.print( patient.getId() );
      out.write('"');
      out.write('>');
      out.print( patient.getId() );
      out.write("</a></td>\r\n");
      out.write("\t\t<td>");
      out.print( patient.getName() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print( patient.getBloodType() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print( patient.getHeight() );
      out.write("</td>\r\n");
      out.write("\t\t<td><a href=\"displayPatientDeleteConfirm?id=");
      out.print( patient.getId() );
      out.write("\">削除</a></td>\r\n");
      out.write("\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br />\r\n");
      out.write("<a href =\"displayPatientCreate\">患者を追加する</a>\r\n");
      out.write("<br /><br />\r\n");
      out.write("<a href =\"index.jsp\">メインメニューに戻る</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
