/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-08-30 04:19:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import jp.co.mtrx.hms.service.*;
import jp.co.mtrx.hms.model.*;

public final class patientUpdateConfirm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset = Shift_JIS;charset=Shift_JIS");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>患者追加</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>患者追加</h1>\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");

		//String id =(String)request.getAttribute("id");
		//String name = (String)request.getAttribute("name");
		//String bloodType = (String)request.getAttribute("bloodType");
		//String height = (String)request.getAttribute("height");
		
		String id = (String)session.getAttribute("id");
		String name = (String)session.getAttribute("name");
		String bloodType = (String)session.getAttribute("bloodType");
		String height = (String)session.getAttribute("height");
		System.out.println("JSP :" + getClass().getName());
		
		
		
		
		
		
		
		Service service = (Service)application.getAttribute("service");
		Patient patient = service.getPatient(Integer.parseInt(id));
 
      out.write("\t\r\n");
      out.write("Before :<br />\r\n");
      out.write("<table border=\"1\" width=\"400\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\">ID</td>\r\n");
      out.write("\t\t<td width=\"50%\">");
      out.print( id );
      out.write("</td>\r\n");
      out.write("\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\">名前</td>\r\n");
      out.write("\t\t<td width=\"50%\">");
      out.print( patient.getName() );
      out.write("</td>\r\n");
      out.write("\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\">血液型</td>\r\n");
      out.write("\t\t<td width=\"50%\">");
      out.print( patient.getBloodType() );
      out.write("</td>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\">身長</td>\r\n");
      out.write("\t\t<td width=\"50%\">");
      out.print( patient.getHeight() );
      out.write(" cm</td>\r\n");
      out.write("\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");
      out.write("After :<br />\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"400\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\">ID</td>\r\n");
      out.write("\t\t<td width=\"50%\">");
      out.print( id );
      out.write("</td>\r\n");
      out.write("\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\">名前</td>\r\n");
      out.write("\t\t<td width=\"50%\">");
      out.print( name );
      out.write("</td>\r\n");
      out.write("\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\">血液型</td>\r\n");
      out.write("\t\t<td width=\"50%\">");
      out.print( bloodType );
      out.write("</td>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\">身長</td>\r\n");
      out.write("\t\t<td width=\"50%\">");
      out.print( height );
      out.write(" cm</td>\r\n");
      out.write("\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br/>\r\n");
      out.write("<form name=\"patientUpdateForm1\" method=\"POST\" action=\"submitPatientUpdate\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"name\" value=\"");
      out.print( name );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bloodType\" value=\"");
      out.print( bloodType );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"height\" value=\"");
      out.print( height );
      out.write("\">\r\n");
      out.write("\t<input type=\"submit\" name=\"submit\" value=\"更新実行\">\r\n");
      out.write("</form>\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("<form name=\"patientCreateForm2\" method=\"POST\" action=\"displayPatientUpdate\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"name\" value=\"");
      out.print( name );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bloodType\" value=\"");
      out.print( bloodType );
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"height\" value=\"");
      out.print( height );
      out.write("\">\r\n");
      out.write("\t<input type=\"submit\" name=\"submit\" value=\"入力しなおす\">\r\n");
      out.write("</form>\r\n");
      out.write("<br /><br />\r\n");
      out.write("<a href=\"displayPatientList\">患者一覧に戻る</a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
